image: gitlab.sai.jku.at:5050/booleguru/builder/image:latest

stages:
  - package
  - deploy

debian-package-job:
  stage: package
  script:
    - mkdir -p build-release
    - cmake -Bbuild-release -S. -DCMAKE_BUILD_TYPE=Release
    - make -Cbuild
    - cpack -Bbuild-release -G DEB
  artifacts:
    - *.deb

pages:
  stage: deploy
  script:
    - mkdir -p build
    - cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release
    - make -C build sphinx
    - mv build/docs/sphinx public
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
